version: "3"
services:
  data-access-api:
    build:
      context: .
    image: registry.wacodis.demo.52north.org/data-access-api:1.0.0
    ports:
      - 8080:8080
    environment: 
      - spring.rabbitmq.host=eum-dcsi.demo.52north.org
