name: Build WaCoDiS Data Access

on: 
  push:
    branches: 
      - master
      - develop

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy: 
      matrix:
        os: [ubuntu-latest]
        jdk-version: [1.8]

    steps:
    - name: Set up JDK ${{matrix.jdk-version}}
      uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.jdk-version}}
    - name: Checkout Data Access
      uses: actions/checkout@v2
    - name: Cache Maven dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build Data Access with Maven and JDK ${{matrix.jdk-version}} on ${{matrix.os}}
      run: mvn -B clean package --file pom.xml
